version: '3'
services:
  dynamic-dns-namecheap:
    build: .
    image: dynamic-dns-namecheap:latest
    container_name: dynamic-dns-namecheap
    command: ["-hosts=host1,host2", "-domain_name=mydomain.com", "-ddns_password=mysecretpassword"]
